// Generated by gencpp from file gazebo_model_collision_plugin/Contact.msg
// DO NOT EDIT!


#ifndef GAZEBO_MODEL_COLLISION_PLUGIN_MESSAGE_CONTACT_H
#define GAZEBO_MODEL_COLLISION_PLUGIN_MESSAGE_CONTACT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace gazebo_model_collision_plugin
{
template <class ContainerAllocator>
struct Contact_
{
  typedef Contact_<ContainerAllocator> Type;

  Contact_()
    : header()
    , objects_hit()  {
    }
  Contact_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , objects_hit(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _objects_hit_type;
  _objects_hit_type objects_hit;





  typedef boost::shared_ptr< ::gazebo_model_collision_plugin::Contact_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gazebo_model_collision_plugin::Contact_<ContainerAllocator> const> ConstPtr;

}; // struct Contact_

typedef ::gazebo_model_collision_plugin::Contact_<std::allocator<void> > Contact;

typedef boost::shared_ptr< ::gazebo_model_collision_plugin::Contact > ContactPtr;
typedef boost::shared_ptr< ::gazebo_model_collision_plugin::Contact const> ContactConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gazebo_model_collision_plugin::Contact_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gazebo_model_collision_plugin::Contact_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gazebo_model_collision_plugin

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'gazebo_model_collision_plugin': ['/home/anshul2/Desktop/poseflow-pie/gazebo_sim/src/gazebo_model_collision_plugin/msgs']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_model_collision_plugin::Contact_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_model_collision_plugin::Contact_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gazebo_model_collision_plugin::Contact_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gazebo_model_collision_plugin::Contact_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_model_collision_plugin::Contact_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_model_collision_plugin::Contact_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gazebo_model_collision_plugin::Contact_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5922a8c08ae2d9e53f76163e11e8c78c";
  }

  static const char* value(const ::gazebo_model_collision_plugin::Contact_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5922a8c08ae2d9e5ULL;
  static const uint64_t static_value2 = 0x3f76163e11e8c78cULL;
};

template<class ContainerAllocator>
struct DataType< ::gazebo_model_collision_plugin::Contact_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gazebo_model_collision_plugin/Contact";
  }

  static const char* value(const ::gazebo_model_collision_plugin::Contact_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gazebo_model_collision_plugin::Contact_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
string[] objects_hit \n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::gazebo_model_collision_plugin::Contact_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gazebo_model_collision_plugin::Contact_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.objects_hit);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Contact_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gazebo_model_collision_plugin::Contact_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gazebo_model_collision_plugin::Contact_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "objects_hit[]" << std::endl;
    for (size_t i = 0; i < v.objects_hit.size(); ++i)
    {
      s << indent << "  objects_hit[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.objects_hit[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // GAZEBO_MODEL_COLLISION_PLUGIN_MESSAGE_CONTACT_H
